apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: johnojabo1/database
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   value: my-secret-pw
        # - name: MYSQL_USER
        #   value: wordpress
        # - name: MYSQL_PASSWORD
        #   value: my-secret-pw
        # - name: MYSQL_DATABASE
        #   value: wordpress
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: dev
spec:
  selector:
    app: database
  ports:
    - name: database
      port: 27017
      targetPort: 27017

